In [1]:
#array manipulation

In [2]:
#array manipulation - changing shape

In [6]:
import numpy as np
a = np.arange(9)
print('The original array: ')
print(a)
print()

b= a.reshape(3,3)
print('The modified array: ')
print(b)

The original array: 
[0 1 2 3 4 5 6 7 8]

The modified array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [11]:
b.flatten(order="F")


array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [12]:
b.flatten(order="C")

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
b.flatten(order="A")

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
print(np.transpose(a))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [17]:
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
c = b.reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
np.rollaxis(c,1,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
np.swapaxes(c,1,2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])